//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ContactLocationAutoTagReceiver {


  public partial class ContactListAutoTagsEntitiesDataContext : Microsoft.SharePoint.Linq.DataContext {

    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion

    public ContactListAutoTagsEntitiesDataContext(string requestUrl) :
      base(requestUrl) {
      this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ListAttribute(Name = "Contact List with Automatic Tags")]
    public Microsoft.SharePoint.Linq.EntityList<ContactListWithAutomaticTagsContact> ContactListWithAutomaticTags {
      get {
        return this.GetList<ContactListWithAutomaticTagsContact>("Contact List with Automatic Tags");
      }
    }
  }

  /// <summary>
  /// Create a new list item.
  /// </summary>
  [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Item", Id = "0x01")]
  [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(Contact))]
  public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {

    private System.Nullable<int> _id;

    private System.Nullable<int> _version;

    private string _path;

    private Microsoft.SharePoint.Linq.EntityState _entityState;

    private System.Collections.Generic.IDictionary<string, object> _originalValues;

    private string _title;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
      get {
        return this._entityState;
      }
      set {
        if ((value != this._entityState)) {
          this._entityState = value;
        }
      }
    }

    System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
      get {
        if ((null == this._originalValues)) {
          this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
        }
        return this._originalValues;
      }
    }

    public Item() {
      this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "ID", Storage = "_id", ReadOnly = true, FieldType = "Counter")]
    public System.Nullable<int> Id {
      get {
        return this._id;
      }
      set {
        if ((value != this._id)) {
          this.OnPropertyChanging("Id", this._id);
          this._id = value;
          this.OnPropertyChanged("Id");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "owshiddenversion", Storage = "_version", ReadOnly = true, FieldType = "Integer")]
    public System.Nullable<int> Version {
      get {
        return this._version;
      }
      set {
        if ((value != this._version)) {
          this.OnPropertyChanging("Version", this._version);
          this._version = value;
          this.OnPropertyChanged("Version");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FileDirRef", Storage = "_path", ReadOnly = true, FieldType = "Lookup", IsLookupValue = true)]
    public string Path {
      get {
        return this._path;
      }
      set {
        if ((value != this._path)) {
          this.OnPropertyChanging("Path", this._path);
          this._path = value;
          this.OnPropertyChanged("Path");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Title", Storage = "_title", Required = true, FieldType = "Text")]
    public virtual string Title {
      get {
        return this._title;
      }
      set {
        if ((value != this._title)) {
          this.OnPropertyChanging("Title", this._title);
          this._title = value;
          this.OnPropertyChanged("Title");
        }
      }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

    protected virtual void OnPropertyChanged(string propertyName) {
      if ((null != this.PropertyChanged)) {
        this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
      }
    }

    protected virtual void OnPropertyChanging(string propertyName, object value) {
      if ((null == this._originalValues)) {
        this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
      }
      if ((false == this._originalValues.ContainsKey(propertyName))) {
        this._originalValues.Add(propertyName, value);
      }
      if ((null != this.PropertyChanging)) {
        this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
      }
    }
  }

  /// <summary>
  /// Store information about a business or personal contact.
  /// </summary>
  [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Contact", Id = "0x0106")]
  [Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type = typeof(ContactListWithAutomaticTagsContact))]
  public partial class Contact : Item {

    private string _lastName;

    private string _lastName0;

    private string _firstName;

    private string _fullName;

    protected string _eMail;

    private string _company;

    private string _jobTitle;

    private string _businessPhone;

    private string _homePhone;

    private string _mobileNumber;

    private string _faxNumber;

    private string _address;

    private string _city;

    private string _stateProvince;

    private string _zIPPostalCode;

    private string _countryRegion;

    private string _webPage;

    private string _comments;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    public Contact() {
      this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "LinkTitle", Storage = "_lastName", ReadOnly = true, FieldType = "Computed")]
    public string LastName {
      get {
        return this._lastName;
      }
      set {
        if ((value != this._lastName)) {
          this.OnPropertyChanging("LastName", this._lastName);
          this._lastName = value;
          this.OnPropertyChanged("LastName");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "LinkTitleNoMenu", Storage = "_lastName0", ReadOnly = true, FieldType = "Computed")]
    public string LastName0 {
      get {
        return this._lastName0;
      }
      set {
        if ((value != this._lastName0)) {
          this.OnPropertyChanging("LastName0", this._lastName0);
          this._lastName0 = value;
          this.OnPropertyChanged("LastName0");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FirstName", Storage = "_firstName", FieldType = "Text")]
    public string FirstName {
      get {
        return this._firstName;
      }
      set {
        if ((value != this._firstName)) {
          this.OnPropertyChanging("FirstName", this._firstName);
          this._firstName = value;
          this.OnPropertyChanged("FirstName");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "FullName", Storage = "_fullName", FieldType = "Text")]
    public string FullName {
      get {
        return this._fullName;
      }
      set {
        if ((value != this._fullName)) {
          this.OnPropertyChanging("FullName", this._fullName);
          this._fullName = value;
          this.OnPropertyChanged("FullName");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "EMail", Storage = "_eMail", FieldType = "Text")]
    public virtual string EMail {
      get {
        return this._eMail;
      }
      set {
        if ((value != this._eMail)) {
          this.OnPropertyChanging("EMail", this._eMail);
          this._eMail = value;
          this.OnPropertyChanged("EMail");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Company", Storage = "_company", FieldType = "Text")]
    public string Company {
      get {
        return this._company;
      }
      set {
        if ((value != this._company)) {
          this.OnPropertyChanging("Company", this._company);
          this._company = value;
          this.OnPropertyChanged("Company");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "JobTitle", Storage = "_jobTitle", FieldType = "Text")]
    public string JobTitle {
      get {
        return this._jobTitle;
      }
      set {
        if ((value != this._jobTitle)) {
          this.OnPropertyChanging("JobTitle", this._jobTitle);
          this._jobTitle = value;
          this.OnPropertyChanged("JobTitle");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkPhone", Storage = "_businessPhone", FieldType = "Text")]
    public string BusinessPhone {
      get {
        return this._businessPhone;
      }
      set {
        if ((value != this._businessPhone)) {
          this.OnPropertyChanging("BusinessPhone", this._businessPhone);
          this._businessPhone = value;
          this.OnPropertyChanged("BusinessPhone");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "HomePhone", Storage = "_homePhone", FieldType = "Text")]
    public string HomePhone {
      get {
        return this._homePhone;
      }
      set {
        if ((value != this._homePhone)) {
          this.OnPropertyChanging("HomePhone", this._homePhone);
          this._homePhone = value;
          this.OnPropertyChanged("HomePhone");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "CellPhone", Storage = "_mobileNumber", FieldType = "Text")]
    public string MobileNumber {
      get {
        return this._mobileNumber;
      }
      set {
        if ((value != this._mobileNumber)) {
          this.OnPropertyChanging("MobileNumber", this._mobileNumber);
          this._mobileNumber = value;
          this.OnPropertyChanged("MobileNumber");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkFax", Storage = "_faxNumber", FieldType = "Text")]
    public string FaxNumber {
      get {
        return this._faxNumber;
      }
      set {
        if ((value != this._faxNumber)) {
          this.OnPropertyChanging("FaxNumber", this._faxNumber);
          this._faxNumber = value;
          this.OnPropertyChanged("FaxNumber");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkAddress", Storage = "_address", FieldType = "Note")]
    public string Address {
      get {
        return this._address;
      }
      set {
        if ((value != this._address)) {
          this.OnPropertyChanging("Address", this._address);
          this._address = value;
          this.OnPropertyChanged("Address");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkCity", Storage = "_city", FieldType = "Text")]
    public string City {
      get {
        return this._city;
      }
      set {
        if ((value != this._city)) {
          this.OnPropertyChanging("City", this._city);
          this._city = value;
          this.OnPropertyChanged("City");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkState", Storage = "_stateProvince", FieldType = "Text")]
    public string StateProvince {
      get {
        return this._stateProvince;
      }
      set {
        if ((value != this._stateProvince)) {
          this.OnPropertyChanging("StateProvince", this._stateProvince);
          this._stateProvince = value;
          this.OnPropertyChanged("StateProvince");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkZip", Storage = "_zIPPostalCode", FieldType = "Text")]
    public string ZIPPostalCode {
      get {
        return this._zIPPostalCode;
      }
      set {
        if ((value != this._zIPPostalCode)) {
          this.OnPropertyChanging("ZIPPostalCode", this._zIPPostalCode);
          this._zIPPostalCode = value;
          this.OnPropertyChanged("ZIPPostalCode");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WorkCountry", Storage = "_countryRegion", FieldType = "Text")]
    public string CountryRegion {
      get {
        return this._countryRegion;
      }
      set {
        if ((value != this._countryRegion)) {
          this.OnPropertyChanging("CountryRegion", this._countryRegion);
          this._countryRegion = value;
          this.OnPropertyChanged("CountryRegion");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "WebPage", Storage = "_webPage", FieldType = "Url")]
    public string WebPage {
      get {
        return this._webPage;
      }
      set {
        if ((value != this._webPage)) {
          this.OnPropertyChanging("WebPage", this._webPage);
          this._webPage = value;
          this.OnPropertyChanged("WebPage");
        }
      }
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Comments", Storage = "_comments", FieldType = "Note")]
    public string Comments {
      get {
        return this._comments;
      }
      set {
        if ((value != this._comments)) {
          this.OnPropertyChanging("Comments", this._comments);
          this._comments = value;
          this.OnPropertyChanged("Comments");
        }
      }
    }
  }

  /// <summary>
  /// Store information about a business or personal contact.
  /// </summary>
  [Microsoft.SharePoint.Linq.ContentTypeAttribute(Name = "Contact", Id = "0x0106", List = "Contact List with Automatic Tags")]
  public partial class ContactListWithAutomaticTagsContact : Contact {

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate();
    partial void OnCreated();
    #endregion

    public ContactListWithAutomaticTagsContact() {
      this.OnCreated();
    }

    [Microsoft.SharePoint.Linq.ColumnAttribute(Name = "Email", Storage = "_eMail", FieldType = "Text")]
    public override string EMail {
      get {
        return this._eMail;
      }
      set {
        if ((value != this._eMail)) {
          this.OnPropertyChanging("EMail", this._eMail);
          this._eMail = value;
          this.OnPropertyChanged("EMail");
        }
      }
    }
  }
}