<%@ Page MasterPageFile="~masterurl/default.master" %> 
      
<asp:Content ContentPlaceHolderId="PlaceHolderAdditionalPageHead" runat="server">

  <link href="styles.css" rel="stylesheet" type="text/css" />
  <link type="text/css" href="jquery/css/ui-lightness/jquery-ui-1.8.2.custom.css" rel="stylesheet" />	
  <script type="text/javascript" src="jquery/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="jquery/js/jquery-ui-1.8.2.custom.min.js"></script>	  
  <script type="text/javascript" src="PageTemplate4.aspx.js"></script>	  

</asp:Content>      
         
<asp:Content ContentPlaceHolderId="PlaceHolderMain" runat="server">
	
 
  <div id="PageBanner" >
    <img src="images/WingtipLogo.gif" alt="Wingtip Logo" />
    <span id="PageBannerText" >JQuery Demo</span>
  </div>

   <div id="PageBody" >  
    <div id="RightColumn" >


    	<!-- Tabs -->
		<h2 class="demoHeaders">Tabs</h2>
		<div id="tabs" stle="width:600px;">
			<ul>
				<li><a href="#tabs-1">Picture 1</a></li>
				<li><a href="#tabs-2">Picture 2</a></li>
				<li><a href="#tabs-3">Picture 3</a></li>
			</ul>
			<div id="tabs-1"><img src="images/TheEarlyDays.jpg" alt="Back when we were young" /></div>
			<div id="tabs-2"><img src="images/SalesTeam.jpg" alt="Nothing like a group of young assertive sales professionals" /></div>
			<div id="tabs-3"><img src="images/SalesmanOfTheYear.jpg" alt="This guys knows how to sell" /></div>
		</div>


    <!-- Accordion -->
		<h2 class="demoHeaders">Accordion</h2>
		<div id="accordion">
			<div>
				<h3><a href="#">The Early Days</a></h3>
				<div><img src="images/TheEarlyDays.jpg" alt="Back when we were young" /></div>
			</div>
			<div>
				<h3><a href="#">Wingtip Sales Team</a></h3>
				<div><img src="images/SalesTeam.jpg" alt="Nothing like a group of young assertive sales professionals" /></div>
			</div>
			<div>
				<h3><a href="#">Salesman of the Year</a></h3>
				<div><img src="images/SalesmanOfTheYear.jpg" alt="This guys knows how to sell" /></div>
			</div>
		</div>

    <div>&nbsp;</div>
    
    </div>

    <div id="LeftColumn" >
      
		<!-- Animation -->
		<h2 class="demoHeaders">Animation</h2>	  
    <p><a href="#" id="start">Start Animation</a></p>
    <div id="box"
      style="background:#9F002D;height:100px;width:100px;position:relative">
    </div>

		<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
		<h2 class="demoHeaders">Dialog</h2>
		<p><a href="#" id="dialog_link" class="ui-state-default ui-corner-all">Open Dialog</a></p>

	<!-- ui-dialog -->
		<div id="dialog" title="Dialog Title">
			<p>Congratulations. You have invoked this very special dialog that has no purpose or consequence.</p>
		</div>			


    </div>
	
		
		
  </div>

</asp:Content>